config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Rutas de Sideqik
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :todo_list
  
  devise_for :users, controllers: { omniauth_callbacks:  'users/omniauth_callbacks' }
  
  root 'todo_list#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
require 'csv'

class TodoList < ApplicationRecord
  validates :title,:description, presence: true
  belongs_to :user

  def self.to_csv
    attributes = %w{title description done_homework}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |todo_list|
        csv << attributes.map{ |attr| todo_list.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      todo_list_hash = row.to_hash
      todo_list = find_or_create_by!(title: todo_list_hash['title'], description: todo_list_hash['description'], done_homework: todo_list_hash['done_homework'])
      todo_list.update_attributes(todo_list_hash)
    end
  end

  scope :completed, -> { where(done_homework: true) }
  scope :pending, -> { where(done_homework: false) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
        
  has_one_attached :avatar
  has_many :todo_lists
  validate :avatar_validation

  def avatar_validation
    if avatar.attached?
      if avatar.blob.byte_size > 1000000
        avatar.purge
        errors[:base] << 'Too big'
      elsif !avatar.blob.content_type.starts_with?('image/')
        avatar.purge
        errors[:base] << 'Wrong format'
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if(data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   
      user.image = auth.info.image 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      attributes = [:name, :surname,:username, :email, :avatar]
      devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
      devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end
end

app/controllers/concerns/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/todo_list_controller.rb
class TodoListController < ApplicationController
  def index    
    @todo_list = TodoList.all
    @todo_list_done_homework = current_user.todo_lists.completed 
    @todo_list_pending_homework = current_user.todo_lists.pending

    respond_to do |format|
      format.html
      format.pdf do
        pdf = TodoListPdf.new(@todo_list)
        send_data pdf.render, filename: 'todo_lists.pdf', type: 'application/pdf', disposition: 'inline'
      end 

      format.csv { send_data @todo_list&.to_csv, filename: "todo_list_#{Date.today}.csv" }
    end
  end

  def new 
    @todo_list = TodoList.new
  end

  def edit 
    @todo_list = TodoList.find(params[:id])
  end

  def create      
    @todo_list = TodoList.new(todo_lists_params.merge(user_id: current_user.id))

    if @todo_list.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update        
    if TodoList.find(params[:id]).update(todo_lists_params.merge(user_id: current_user.id))
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def show
    @todo_list = TodoList.find(params[:id]) 
  end 

  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy
    redirect_to root_path
  end

  private
  def todo_lists_params
    params.require(:todo_list).permit(:title, :description, :done_homework) 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_list_helper.rb
module TodoListHelper
  def define_image
    if resource.avatar.attached? 
      image_tag(resource.avatar.variant(resize: "150x150"))
    elsif resource.image
      image_tag(resource.image) 
    else
      value_without_image = '<h3> Sin imagen </h3>'.html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challengeruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class='navbar-text pull-right'>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link'  %> |
      <%= link_to 'Login', new_user_session_path, class: 'navbar-link'  %>
    <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/todo_list/_form.html.erb
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :done_homework %>
  <%= f.check_box :done_homework %>  
</p>

<p>
  <%= f.submit %>
</p> 

app/views/todo_list/edit.html.erb
<h1>Edit</h1>

<%= form_with model: @todo_list, local: true do |f| %>
    <%= render(partial: 'form', locals: {f: f})%>
<% end %>
 
<%= link_to 'Back', action: :index %>

app/views/todo_list/index.html.erb
<h1>¡Bienvenido!</h1>
<%= link_to 'Crear nuevo', :action => :new %>
<p><%= link_to('Generate Report CSV', todo_list_index_path(format: 'csv')) %></p>
<p><%= link_to('Generate Report PDF', todo_list_index_path(format: 'pdf')) %></p>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Edit</th>
        <th>Show</th>
        <th>Delete</th>
    </tr>

    <tr>
        <td colspan='4'><b>Done homeworks</b></td>
    </tr>
    <% @todo_list_done_homework&.each do |todo| %>
        <tr>
            <td><%= todo.title %></td>
            <td><%= todo.description %></td>
            <td><%= link_to 'Edit', edit_todo_list_path(todo) %></td>
            <td><%= link_to 'Show', todo_list_path(todo) %></td>
            <td><%= link_to 'Destroy', todo_list_path(todo), 
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %> 

    <tr>
        <td colspan='4'><b>Pending homeworks</b></td>
    </tr>
    
    <% @todo_list_pending_homework&.each do |todo| %>
        <tr>
            <td><%= todo.title %></td>
            <td><%= todo.description %></td>
            <td><%= link_to 'Edit', edit_todo_list_path(todo) %></td>
            <td><%= link_to 'Show', todo_list_path(todo) %></td>
            <td><%= link_to 'Destroy', todo_list_path(todo), 
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %> 

</table>

app/views/todo_list/new.html.erb
<h1>New To do</h1>
 
<%= form_for :todo_list, url: { action: :create }  do |f| %>
    <%= render(partial: 'form', locals: { f: f })%>
<% end %>

<%= link_to 'Back', action: :index %>

app/views/todo_list/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>
<%= link_to 'Back', action: :index %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>